| sketch |
sketch _ DrGeoSketch new.
sketch text:'Desargues configuration' at:(-4@4).
sketch text:'10 points   3lines/point' at:(-4@3).
sketch text:' 3 points/line    10 lines' at:(-4@2).
sketch text:'section plane/complete 5-points' at:(-4@1).
sketch text:'P center intersection DE and plane' at:(-4@0).
sketch text:'p axis intersection ABC and plane' at:(-4@-1).
sketch text:'planes DEA,DEB,DEC' at:(-4@-2).
